#! /bin/bash

files=`find $1 -a -maxdepth 1 -type f`
declare -a sameFiles
let count=0
for file in $files
do
    echo $file
    for file2 in $files
    do
	# if the 2 files have the same content
	if diff $file $file2 >/dev/null
	then
	    echo "same content"
	    sameFiles+=$file2
	else
	    echo "diff file content"
	fi
    done
    echo $sameFiles

    # not working following line
    length=${#sameFiles[@]}
    echo ${length}
    if [ ${length} -gt 1 ]
    then
	echo "multiple same files to link"
    fi
 
    # reset same files
    sameFiles=()
    echo "\n"
done

